language: r
r:
  - oldrel
  - release
  - devel
cache: packages
r_github_packages: r-lib/pkgdown
after_success:
  - chmod +x ./build_docs.sh
  - ./build_docs.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  on:
    branch: master
notifications:
  email:
    on_success: change
    on_failure: always
  slack: langcog:n48V2GKFt8a0c39qExWBr8ri
