language: r
cache: packages
use_devtools: true
apt_packages:
  - libharfbuzz-dev
  - libfribidi-dev
r_packages:
  - devtools
  - pkgdown
before_install:
  - Rscript -e 'install.packages(c("devtools"));if (!all(c("devtools") %in% installed.packages())) { q(status = 1, save = "no")}'
  - Rscript -e 'install.packages(c("pkgdown"));if (!all(c("pkgdown") %in% installed.packages())) { q(status = 1, save = "no")}'
install:
  - R -e 'devtools::install_deps(dep = T)'
script:
  - R CMD build .
  - travis_wait 50 R CMD check *tar.gz --as-cran
after_success:
  - chmod +x ./build_docs.sh
  - travis_wait 30 ./build_docs.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  on:
    branch: master
notifications:
  email:
    on_success: change
    on_failure: always
  slack: langcog:n48V2GKFt8a0c39qExWBr8ri
